[package]
name = "grpc"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
chrono.workspace = true
log.workspace = true
prost.workspace = true
serde_json.workspace = true
server.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tonic-prost.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true

[lints]
workspace = true
